# Generated by Django 5.0.6 on 2024-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=6),
        ),
    ]
