# Generated by Django 5.0.6 on 2024-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_alter_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
