# Generated by Django 5.0.6 on 2024-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
