# Generated by Django 5.0.6 on 2024-06-25 18:48

import appname.models.task
import appname.models.team_invitation
import appname.models.team_member
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_teaminvitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, validators=[appname.models.task.validate_description]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[appname.models.task.validate_title]),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='email',
            field=models.EmailField(max_length=254, validators=[appname.models.team_invitation.validate_email]),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='appname.team', validators=[appname.models.team_invitation.validate_team]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='appname.team', validators=[appname.models.team_member.validate_team]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[appname.models.team_member.validate_user]),
        ),
    ]
